language: dart
dart: dev

env:
  global:
    - DIR="example lib test"
  matrix:
    - CI_TASK="dartfmt --set-exit-if-changed -n $DIR"
    - CI_TASK="dartanalyzer --fatal-warnings $DIR"
    - CI_TASK="pub run test"
    - CI_TASK="tool/travis.sh"

cache:
  directories:
  - $HOME/.pub-cache

script: $CI_TASK
