include: package:pedantic/analysis_options.1.9.0.yaml
linter:
  rules:
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_constructor_bodies
    - empty_statements
    - empty_statements
    - implementation_imports
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - only_throw_errors
    - prefer_final_fields
    - prefer_is_not_empty
    - prefer_single_quotes
    - slash_for_doc_comments
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unrelated_type_equality_checks
    - valid_regexps
